sample = {   
    'com.tencent.news': {   'baidu': {   'debug': {   False: {   'kill_tracer': True,
                                                                 'trace_succ': True,
                                                                 'tracer_child': True,
                                                                 'tracer_name': 'com.tencent.news',
                                                                 'tracer_pid': '1856'},
                                                      True: {   'trace_succ': False},
                                                      'can_trace': False,
                                                      'tested': True},
                                         'dynamic_loading': {   'act_num': '135',
                                                                'cls_num': '3',
                                                                'flag': 'Baidu',
                                                                'ratio': '1.0'},
                                         'log_clear': '00000',
                                         'memory': 54274.333333333336,
                                         'network': [   {   'city': 'Guangzhou',
                                                            'country': 'CN',
                                                            'hostname': 'No Hostname',
                                                            'ip': '112.90.78.190',
                                                            'loc': '23.1167,113.2500',
                                                            'org': 'AS17623 China Unicom Shenzen network',
                                                            'region': 'Guangdong'},
                                                        {   'city': 'Guangzhou',
                                                            'country': 'CN',
                                                            'hostname': 'No Hostname',
                                                            'ip': '112.90.83.107',
                                                            'loc': '23.1167,113.2500',
                                                            'org': 'AS17623 China Unicom Shenzen network',
                                                            'region': 'Guangdong'},
                                                        {   'city': 'Guangzhou',
                                                            'country': 'CN',
                                                            'hostname': 'No Hostname',
                                                            'ip': '163.177.89.171',
                                                            'loc': '23.1167,113.2500',
                                                            'org': 'AS17623 China Unicom Shenzen network',
                                                            'region': 'Guangdong'},
                                                        {   'city': 'Shenzhen',
                                                            'country': 'CN',
                                                            'hostname': 'No Hostname',
                                                            'ip': '182.254.34.42',
                                                            'loc': '22.5333,114.1333',
                                                            'org': 'AS45090 Shenzhen Tencent Computer Systems Company Limited',
                                                            'region': 'Guangdong'},
                                                        {   'city': 'Guangzhou',
                                                            'country': 'CN',
                                                            'hostname': 'No Hostname',
                                                            'ip': '59.37.96.68',
                                                            'loc': '23.1167,113.2500',
                                                            'org': 'AS4816 China Telecom (Group)',
                                                            'region': 'Guangdong'},
                                                        {   'city': 'Guangzhou',
                                                            'country': 'CN',
                                                            'hostname': 'No Hostname',
                                                            'ip': '219.133.60.185',
                                                            'loc': '23.1167,113.2500',
                                                            'org': 'AS4816 China Telecom (Group)',
                                                            'region': 'Guangdong'}],
                                         'permission': [   'android.permission.READ_SMS',
                                                           'android.permission.SEND_SMS',
                                                           'android.permission.MOUNT_UNMOUNT_FILESYSTEMS',
                                                           'android.permission.ACCESS_FINE_LOCATION',
                                                           'android.permission.ACCESS_COARSE_LOCATION',
                                                           'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS',
                                                           'android.permission.CHANGE_WIFI_STATE',
                                                           'android.permission.WIFI_STATE_CHANGED',
                                                           'android.permission.WRITE_SETTINGS',
                                                           'android.permission.RECEIVE_BOOT_COMPLETED',
                                                           'android.permission.ACCESS_NETWORK_STATE',
                                                           'android.permission.INTERNET',
                                                           'android.permission.WRITE_EXTERNAL_STORAGE',
                                                           'android.permission.READ_PHONE_STATE',
                                                           'android.permission.ACCESS_WIFI_STATE',
                                                           'android.permission.CHANGE_NETWORK_STATE',
                                                           'android.permission.GET_TASKS',
                                                           'android.permission.VIBRATE',
                                                           'android.permission.WAKE_LOCK',
                                                           'com.android.launcher.permission.INSTALL_SHORTCUT',
                                                           'com.android.launcher.permission.UNINSTALL_SHORTCUT',
                                                           'com.android.launcher.permission.READ_SETTINGS',
                                                           'com.android.launcher2.permission.READ_SETTINGS',
                                                           'android.permission.RESTART_PACKAGES',
                                                           'android.permission.DISABLE_KEYGUARD',
                                                           'android.permission.SYSTEM_ALERT_WINDOW',
                                                           'com.tencent.news.permisson.ACTION',
                                                           'android.permission.RECORD_AUDIO',
                                                           'android.permission.CALL_PHONE',
                                                           'com.tencent.news.house.permission.RECEIVE_BROADCAST'],
                                         'proc_num': 4,
                                         'signature': 'Signature Not Protected',
                                         'size': 13372226L,
                                         'so': True,
                                         'startup_cost': '0.907999999996',
                                         'tamper': '111'},
                            'bangcle': {   'debug': {   False: {   'kill_tracer': True,
                                                                   'trace_succ': False,
                                                                   'tracer_child': True,
                                                                   'tracer_name': 'com.tencent.news',
                                                                   'tracer_pid': '2513'},
                                                        True: {   'trace_succ': False},
                                                        'can_trace': False,
                                                        'tested': True},
                                           'dynamic_loading': {   'act_num': '136',
                                                                  'cls_num': '10',
                                                                  'flag': 'Bangcle',
                                                                  'ratio': '1.0'},
                                           'log_clear': '00000',
                                           'memory': 64683.333333333336,
                                           'network': [   {   'city': 'Guangzhou',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '112.90.78.190',
                                                              'loc': '23.1167,113.2500',
                                                              'org': 'AS17623 China Unicom Shenzen network',
                                                              'region': 'Guangdong'},
                                                          {   'city': 'Guangzhou',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '113.108.90.44',
                                                              'loc': '23.1167,113.2500',
                                                              'org': 'AS4134 No.31,Jin-rong Street',
                                                              'region': 'Guangdong'},
                                                          {   'city': 'Shenzhen',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '182.254.3.181',
                                                              'loc': '22.5333,114.1333',
                                                              'org': 'AS45090 Shenzhen Tencent Computer Systems Company Limited',
                                                              'region': 'Guangdong'},
                                                          {   'city': 'Beijing',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '120.132.51.4',
                                                              'loc': '39.9289,116.3883',
                                                              'org': 'AS23724 IDC, China Telecommunications Corporation',
                                                              'region': 'Beijing'},
                                                          {   'city': 'Guangzhou',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '163.177.89.171',
                                                              'loc': '23.1167,113.2500',
                                                              'org': 'AS17623 China Unicom Shenzen network',
                                                              'region': 'Guangdong'},
                                                          {   'city': 'Guangzhou',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '112.90.83.107',
                                                              'loc': '23.1167,113.2500',
                                                              'org': 'AS17623 China Unicom Shenzen network',
                                                              'region': 'Guangdong'},
                                                          {   'city': 'Guangzhou',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '59.37.96.68',
                                                              'loc': '23.1167,113.2500',
                                                              'org': 'AS4816 China Telecom (Group)',
                                                              'region': 'Guangdong'},
                                                          {   'city': 'Guangzhou',
                                                              'country': 'CN',
                                                              'hostname': 'No Hostname',
                                                              'ip': '219.133.60.185',
                                                              'loc': '23.1167,113.2500',
                                                              'org': 'AS4816 China Telecom (Group)',
                                                              'region': 'Guangdong'}],
                                           'permission': [   'android.permission.READ_SMS',
                                                             'android.permission.SEND_SMS',
                                                             'android.permission.MOUNT_UNMOUNT_FILESYSTEMS',
                                                             'android.permission.ACCESS_FINE_LOCATION',
                                                             'android.permission.ACCESS_COARSE_LOCATION',
                                                             'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS',
                                                             'android.permission.CHANGE_WIFI_STATE',
                                                             'android.permission.WIFI_STATE_CHANGED',
                                                             'android.permission.WRITE_SETTINGS',
                                                             'android.permission.RECEIVE_BOOT_COMPLETED',
                                                             'android.permission.ACCESS_NETWORK_STATE',
                                                             'android.permission.INTERNET',
                                                             'android.permission.WRITE_EXTERNAL_STORAGE',
                                                             'android.permission.READ_PHONE_STATE',
                                                             'android.permission.ACCESS_WIFI_STATE',
                                                             'android.permission.CHANGE_NETWORK_STATE',
                                                             'android.permission.GET_TASKS',
                                                             'android.permission.VIBRATE',
                                                             'android.permission.WAKE_LOCK',
                                                             'com.android.launcher.permission.INSTALL_SHORTCUT',
                                                             'com.android.launcher.permission.UNINSTALL_SHORTCUT',
                                                             'com.android.launcher.permission.READ_SETTINGS',
                                                             'com.android.launcher2.permission.READ_SETTINGS',
                                                             'android.permission.RESTART_PACKAGES',
                                                             'android.permission.DISABLE_KEYGUARD',
                                                             'android.permission.SYSTEM_ALERT_WINDOW',
                                                             'com.tencent.news.permisson.ACTION',
                                                             'android.permission.RECORD_AUDIO',
                                                             'android.permission.CALL_PHONE',
                                                             'com.tencent.news.house.permission.RECEIVE_BROADCAST'],
                                           'proc_num': 6,
                                           'signature': 'Signature Not Protected',
                                           'size': 13542842L,
                                           'so': True,
                                           'startup_cost': '0.419999999998',
                                           'tamper': '111'},
                            'original': {   'debug': {   False: {   'kill_tracer': False,
                                                                    'trace_succ': False,
                                                                    'tracer_child': False,
                                                                    'tracer_name': False,
                                                                    'tracer_pid': False},
                                                         True: {   'trace_succ': True},
                                                         'can_trace': True,
                                                         'tested': True},
                                            'dynamic_loading': {   'act_num': '135',
                                                                   'cls_num': '5722',
                                                                   'flag': 'No-Protection-Detected',
                                                                   'ratio': '0.0'},
                                            'log_clear': '00000',
                                            'memory': 33911.666666666664,
                                            'network': [   {   'city': 'Guangzhou',
                                                               'country': 'CN',
                                                               'hostname': 'No Hostname',
                                                               'ip': '112.90.78.190',
                                                               'loc': '23.1167,113.2500',
                                                               'org': 'AS17623 China Unicom Shenzen network',
                                                               'region': 'Guangdong'},
                                                           {   'city': 'Guangzhou',
                                                               'country': 'CN',
                                                               'hostname': 'No Hostname',
                                                               'ip': '112.90.83.107',
                                                               'loc': '23.1167,113.2500',
                                                               'org': 'AS17623 China Unicom Shenzen network',
                                                               'region': 'Guangdong'},
                                                           {   'city': 'Guangzhou',
                                                               'country': 'CN',
                                                               'hostname': 'No Hostname',
                                                               'ip': '163.177.89.171',
                                                               'loc': '23.1167,113.2500',
                                                               'org': 'AS17623 China Unicom Shenzen network',
                                                               'region': 'Guangdong'},
                                                           {   'city': 'Shenzhen',
                                                               'country': 'CN',
                                                               'hostname': 'No Hostname',
                                                               'ip': '182.254.34.42',
                                                               'loc': '22.5333,114.1333',
                                                               'org': 'AS45090 Shenzhen Tencent Computer Systems Company Limited',
                                                               'region': 'Guangdong'},
                                                           {   'city': 'Guangzhou',
                                                               'country': 'CN',
                                                               'hostname': 'No Hostname',
                                                               'ip': '219.133.60.185',
                                                               'loc': '23.1167,113.2500',
                                                               'org': 'AS4816 China Telecom (Group)',
                                                               'region': 'Guangdong'}],
                                            'permission': [   'android.permission.READ_SMS',
                                                              'android.permission.SEND_SMS',
                                                              'android.permission.MOUNT_UNMOUNT_FILESYSTEMS',
                                                              'android.permission.ACCESS_FINE_LOCATION',
                                                              'android.permission.ACCESS_COARSE_LOCATION',
                                                              'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS',
                                                              'android.permission.CHANGE_WIFI_STATE',
                                                              'android.permission.WIFI_STATE_CHANGED',
                                                              'android.permission.WRITE_SETTINGS',
                                                              'android.permission.RECEIVE_BOOT_COMPLETED',
                                                              'android.permission.ACCESS_NETWORK_STATE',
                                                              'android.permission.INTERNET',
                                                              'android.permission.WRITE_EXTERNAL_STORAGE',
                                                              'android.permission.READ_PHONE_STATE',
                                                              'android.permission.ACCESS_WIFI_STATE',
                                                              'android.permission.CHANGE_NETWORK_STATE',
                                                              'android.permission.GET_TASKS',
                                                              'android.permission.VIBRATE',
                                                              'android.permission.WAKE_LOCK',
                                                              'com.android.launcher.permission.INSTALL_SHORTCUT',
                                                              'com.android.launcher.permission.UNINSTALL_SHORTCUT',
                                                              'com.android.launcher.permission.READ_SETTINGS',
                                                              'com.android.launcher2.permission.READ_SETTINGS',
                                                              'android.permission.RESTART_PACKAGES',
                                                              'android.permission.DISABLE_KEYGUARD',
                                                              'android.permission.SYSTEM_ALERT_WINDOW',
                                                              'com.tencent.news.permisson.ACTION',
                                                              'android.permission.RECORD_AUDIO',
                                                              'android.permission.CALL_PHONE',
                                                              'com.tencent.news.house.permission.RECEIVE_BROADCAST'],
                                            'proc_num': 2,
                                            'size': 12726352L,
                                            'startup_cost': '0.199999999997',
                                            'tamper': '111'}}}
